---
- name: Create a Deep Learning instance
  hosts: localhost
  gather_facts: False
  vars:
    wait: yes
    count: 1
    assign_public_ip: yes
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{vpc_subnet_id}}"
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
- name: Configure instance - get the git then clone the repo
  hosts: launched
  vars:
    ansible_ssh_private_key_file: "{{private_key}}"
    ansible_user: "{{user}}"
  vars_prompt:
    - name: "gitrepo" 
      prompt: "Enter git repo to clone" 
      private: no 
  tasks:
    - name: Configure instance
      git:
        repo: "{{gitrepo}}"
        dest: /home/{{user}}/repo


